version: '3.12'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: MainScores.p

